global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'education_portal'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 60s
    scheme: 'https'
    static_configs:
      - targets: ['educationportal.codehunters.hu']
      - targets: ['dev-educationportal.codehunters.hu']
  - job_name: 'codehunters.hu'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 60s
    scheme: 'https'
    static_configs:
      - targets: [ 'codehunters.hu' ]
  - job_name: 'node_exporter'
    scrape_interval: 60s
    scheme: 'http'
    static_configs:
      - targets: [ 'node-exporter:9100' ]
  - job_name: 'monitoring_app_1'
    scrape_interval: 60s
    scheme: 'http'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'monitoring-app-1:8080' ]
  - job_name: 'monitoring_app_2'
    scrape_interval: 60s
    scheme: 'http'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'monitoring-app-2:8080' ]
